export const ActionTypes = {
  SET_MOVIES: "SET_MOVIES",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  UPDATE_MOVIE: "UPDATE_MOVIE",
   SET_USERS: "SET_USERS",
  REMOVE_USER: "REMOVE_USER",
  UPDATE_USER: "UPDATE_USER",
};
